version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy  
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:  
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  app-network:
    driver: bridge
